name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:    
  CreateDevRelease:
    name: Create Dev Release
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: CI_Push_Main_ProdSS.yaml
          name: test_report
      - uses: actions/upload-artifact@v3
        with:
          name: test_report
          path: test_report.xml
      - name: Create Zip
        run: echo Zipping...
      - name: Create Dev Release
        run: echo Releasing... 
