name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: trstringer/manual-approval@v1
      timeout-minutes: 10
      with:
        secret: ${{ github.TOKEN }}
        approvers: NPLeeWenKang
        minimum-approvals: 1
        issue-title: "Deploying v1.3.5 to prod from staging"
        exclude-workflow-initiator-as-approver: false
