name: Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:    
  CreateDevRelease:
    name: Create Dev Release
    if: github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Download Report
        run: echo Downloading... 
      - name: Create Zip
        run: echo Zipping...
      - name: Create Dev Release
        run: echo Releasing... 
