name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'main'
