name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: NPLeeWenKang
        minimum-approvals: 1
        issue-title: "Deploying v1.3.5 to prod from staging"
        exclude-workflow-initiator-as-approver: false
